### ISSUE TITLE
[Feat] Login/Signup Screen

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Sell-It#18]
Need a Login/Signup Screen for the user Login process.

**Comment by tiger-yash** [comment]
Hello!
I would like to work on this issue, please assign.

**Comment by niloysikdar** [comment]
Assigned @tiger-yash , all the best

**Comment by tiger-yash** [comment]
@niloysikdar can you please share how you want the page to be? Is it alright if I integrate both SignIn and SignUp on the same page?

**Comment by niloysikdar** [comment]
Yeah @tiger-yash , it's fine if you integrate both of them on the same page, otherwise, you can also create two separate route and make them.
